Merged in develop (pull request #98)
Develop

* Merged in API-1010-playground-cambiar-los-asserts- (pull request #94)

    asserts cambiados segun laravel-json-api

    Approved-by: Juan I. Castellano <juanicastellano14@gmail.com>
    Approved-by: Pablo Reyes <reyesoft@gmail.com>

* Merged in feature/boxfile_with_reset_token (pull request #95)

    Feature/boxfile with reset token

    * added

    * feature/boxfile_with_reset_token

    * autofix with new ci

    * reyesoft-ci updated

    * composer updated

    Approved-by: Pablo Reyes <reyesoft@gmail.com>

* Merged in ci/updated (pull request #97)

    Ci/updated

    * added

    * feature/boxfile_with_reset_token

    * autofix with new ci

    * reyesoft-ci updated

    * composer updated

    * ci updated

    * rules applied

    * ci and jsonapi library updated

    * SchemaRelationsTrait removed

    * filter updated

    Approved-by: Jonatan Eseiza <jonatan.eseiza@gmail.com>
    Approved-by: Pablo Reyes <reyesoft@gmail.com>

Approved-by: Pablo Reyes <reyesoft@gmail.com>

diff --git a/runtests b/runtests
--- a/runtests
+++ b/runtests
@@ -1,14 +1,17 @@
 #!/bin/sh
 
-## Copyright (C) 1997-2017 Reyesoft <info@reyesoft.com>.
+## Copyright (C) 1997-2018 Reyesoft <info@reyesoft.com>.
 ## This file is part of a Reyesoft Project. This can not be copied and/or
 ## distributed without the express permission of Reyesoft
 
 # https://stackoverflow.com/questions/16483119/an-example-of-how-to-use-getopts-in-bash?answertab=votes#tab-top
-while getopts ":f" o; do
+while getopts ":ft" o; do
     case "${o}" in
         f)
             f=1
+            ;;
+        t)
+            t=1
             ;;
     esac
 done
@@ -27,12 +30,21 @@ if [ "$?" -eq 0 ] || [ "${f}" ] ; then
         echo "\n ✖  Errors on migrations or generator scripts. \n"
         exit 1
     fi
+
+    ## this project
+    #
 else
-    echo 'Migrations are not required.'
+    echo '\033[1;30m Migrations are not required. \033[0m'
 fi;
 
-phpunit &&
 
-if [ $? -eq 0 ]; then
-    echo "\n 🔎  Don't forget to run \n    composer coverage \n"
-fi
+if [ "${t}" ] ; then
+    phpunit &&
+
+    if [ $? -eq 0 ]; then
+        echo "\n 🔎  Don't forget to run \n    composer coverage \n"
+    fi
+else
+    echo "\n\033[1;33m 💨  For a faster test (only phpunit) run \n    sh runtests -t [-f]\n \033[0m"
+    composer coverage
+fi;
